#!/usr/bin/env ruby -w
# frozen_string_literal: true

# Created by Devon Huxtable <devon.huxtable@gmail.com>, November 2021.

desc 'Builds gems'
task :build do
  system('gem', 'build')
end

desc 'Installs as a Geode'
task install: [:build] do
  FileList['*.gem'].each do |gem|
    system('gem', 'install', gem)
  end
end